services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Authentication\:
        resource: '../../../../src/lib/Authentication/*'

    EzSystems\EzRecommendationClient\Authentication\ExportAuthenticator:
        arguments:
            $credentialsChecker: '@EzSystems\EzRecommendationClient\Config\ExportCredentialsChecker'
