services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzSystems\EzRecommendationClientBundle\Controller\:
        resource: '../../../Controller/*'

    EzSystems\EzRecommendationClientBundle\Controller\ContentController:
        arguments:
            $authenticator: '@EzSystems\EzRecommendationClient\Authentication\ExportAuthenticator'

    EzSystems\EzRecommendationClientBundle\Controller\ContentTypeController:
        arguments:
            $authenticator: '@EzSystems\EzRecommendationClient\Authentication\ExportAuthenticator'

    EzSystems\EzRecommendationClientBundle\Controller\ExportController:
        arguments:
            $authenticator: '@EzSystems\EzRecommendationClient\Authentication\ExportAuthenticator'
        tags:
            - { name: monolog.logger, channel: ez_recommendation }
