services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Config\:
        resource: '../../../../src/lib/Config/*'

    EzSystems\EzRecommendationClient\Config\EzRecommendationClientCredentialsChecker:
        arguments:
            $customerId: '%ez_recommendation.default.recommendation.customer_id%'
            $licenseKey: '%ez_recommendation.default.recommendation.license_key%'

    EzSystems\EzRecommendationClient\Config\ExportCredentialsChecker:
        arguments:
            $method: '%ez_recommendation.export.users_authentication.method%'
            $login: '%ez_recommendation.export.users_authentication.login%'
            $password: '%ez_recommendation.export.users_authentication.password%'

    EzSystems\EzRecommendationClient\Config\RecommendationNotifierCredentialsChecker:
        arguments:
            $serverUri: '%ez_recommendation.default.server_uri%'
            $apiEndpoint: '%ez_recommendation.api_endpoint%'
