services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Event\:
        resource: '../../../../src/lib/Event/*'

    EzSystems\EzRecommendationClient\Event\Listener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, priority: 255 }
            - { name: monolog.logger, channel: ez_recommendation }

    EzSystems\EzRecommendationClient\Event\Listener\SessionBackupListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: monolog.logger, channel: ez_recommendation }

    EzSystems\EzRecommendationClient\Event\Subscriber\RecommendationEventSubscriber:
        tags:
            - { name: kernel.event_subscriber, event: recommendation.response }

    EzSystems\EzRecommendationClient\Event\Subscriber\RecommendationRandomContentEventSubscriber:
        arguments:
            $randomContentTypes: '%ez_recommendation.response.random_content_types%'
        tags:
            - { name: kernel.event_subscriber, event: recommendation.response }
