services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Factory\:
        resource: '../../../../src/lib/Factory/*'

    EzSystems\EzRecommendationClient\Factory\ExportParametersFactory:
        arguments:
            $credentialsResolver: '@EzSystems\EzRecommendationClient\Config\ExportCredentialsResolver'
