services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Field\:
        resource: '../../../../src/lib/Field/*'

    EzSystems\EzRecommendationClient\Field\Value:
        arguments:
            $parameters: {fieldIdentifiers: "%ez_recommendation.field_identifiers%"}
        tags:
            - { name: monolog.logger, channel: ez_recommendation }

    EzSystems\EzRecommendationClient\Field\TypeValue:
        arguments:
            $imageVariationService: '@ezpublish.image_alias.imagine.alias_generator'
            $richHtml5Converter: '@ezpublish.fieldType.ezrichtext.converter.output.xhtml5'
