services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Generator\:
        resource: '../../../../src/lib/Generator/*'
