services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Helper\:
        resource: '../../../../src/lib/Helper/*'

    EzSystems\EzRecommendationClient\Helper\FileSystemHelper:
        arguments:
            $exportDocumentRoot: '%ez_recommendation.export.document_root%'

    EzSystems\EzRecommendationClient\Helper\SiteAccessHelper:
        arguments:
            $siteAccessConfig: '%ez_recommendation.siteaccess_config%'
            $defaultSiteAccessName: '%ezpublish.siteaccess.default%'

    EzSystems\EzRecommendationClient\Helper\ExportProcessRunnerHelper:
        arguments:
            $kernelEnvironment: '%kernel.environment%'
        tags:
            - { name: monolog.logger, channel: ez_recommendation }
