services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Service\:
        resource: '../../../../src/lib/Service/*'

    EzSystems\EzRecommendationClient\Service\SignalSlotService:
        arguments:
            $clientCredentialsChecker: '@EzSystems\EzRecommendationClient\Config\EzRecommendationClientCredentialsChecker'
            $exportCredentialsChecker: '@EzSystems\EzRecommendationClient\Config\ExportCredentialsChecker'
        tags:
            - { name: monolog.logger, channel: ezrecommendation }
