services:
    _defaults:
        autowire: true
        autoconfigure: true

    EzSystems\EzRecommendationClientBundle\Templating\:
        resource: '../../../Templating/*'

    EzSystems\EzRecommendationClientBundle\Templating\Twig\RecommendationExtension:
        public: true
        arguments:
            $credentialsChecker: '@EzSystems\EzRecommendationClient\Config\EzRecommendationClientCredentialsChecker'
        tags:
            - { name: twig.extension }
